---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "./.github/workflows"
    schedule:
      interval: "monthly"
    labels:
      - "housekeeping"
      - "technical"
    groups:
      all-github-actions:
        patterns:
          - "*"
