repos:
    # Sort order of Python imports
    - repo: https://github.com/pycqa/isort
      rev: 6.0.1
      hooks:
          - id: isort
    # Python code formatting
    - repo: https://github.com/psf/black
      rev: 25.1.0
      hooks:
          - id: black
    # Remove unused Python imports
    - repo: https://github.com/myint/autoflake
      rev: v2.3.1
      hooks:
        - id: autoflake
          args: ["--in-place", "--remove-all-unused-imports"]
    # Remove whitespace at line end, ensure newline at the end of files
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0  # Use the ref you want to point at
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
    # Add C++ linting
    - repo: https://github.com/pocc/pre-commit-hooks
      rev: v1.3.5
      hooks:
        - id: clang-format
          args: ["--style=file", "-i"]
      # - id: cppcheck
      #   args: ["--project=tdms/build/compile_commands.json"]
      # - id: cpplint
      #   args: ["--filter=-whitespace/comments,-legal/copyright", "--linelength=120", "--quiet"]
      # suppress whitespace because it conflicts with clang-tidy and doxygen
      # suppress copyright in file headers because we don't require them in the developer docs
      # run quietly so we don't see you doing this if everything is fine
