var arrays_8h =
[
    [ "xyz_vector< T >", "structxyz__vector.html", null ],
    [ "XYZTensor3D< T >", "class_x_y_z_tensor3_d.html", "class_x_y_z_tensor3_d" ],
    [ "XYZVectors", "class_x_y_z_vectors.html", "class_x_y_z_vectors" ],
    [ "MaterialCollection", "class_material_collection.html", null ],
    [ "CCollectionBase", "class_c_collection_base.html", null ],
    [ "CCollection", "class_c_collection.html", null ],
    [ "CMaterial", "class_c_material.html", null ],
    [ "DCollectionBase", "class_d_collection_base.html", null ],
    [ "DCollection", "class_d_collection.html", null ],
    [ "DMaterial", "class_d_material.html", null ],
    [ "DispersiveMultiLayer", "struct_dispersive_multi_layer.html", "struct_dispersive_multi_layer" ],
    [ "Matrix< T >", "class_matrix.html", "class_matrix" ],
    [ "GratingStructure", "class_grating_structure.html", null ],
    [ "Vector< T >", "class_vector.html", null ],
    [ "FrequencyExtractVector", "class_frequency_extract_vector.html", null ],
    [ "FrequencyVectors", "struct_frequency_vectors.html", null ],
    [ "Pupil", "class_pupil.html", null ],
    [ "FieldComponentsVector", "class_field_components_vector.html", "class_field_components_vector" ],
    [ "Vertices", "class_vertices.html", null ],
    [ "DetectorSensitivityArrays", "class_detector_sensitivity_arrays.html", null ],
    [ "CCoefficientMatrix", "class_c_coefficient_matrix.html", null ],
    [ "FullFieldSnapshot", "class_full_field_snapshot.html", "class_full_field_snapshot" ]
];