var dir_31151eb6fe72a8c6f09675be35b4e99c =
[
    [ "argument_parser.h", "argument__parser_8h.html", "argument__parser_8h" ],
    [ "array_init.h", "array__init_8h.html", "array__init_8h" ],
    [ "arrays.h", "arrays_8h.html", "arrays_8h" ],
    [ "cell_coordinate.h", "cell__coordinate_8h.html", "cell__coordinate_8h" ],
    [ "dimensions.h", "dimensions_8h.html", "dimensions_8h" ],
    [ "fdtd_grid_initialiser.h", "fdtd__grid__initialiser_8h.html", "fdtd__grid__initialiser_8h" ],
    [ "field.h", "field_8h.html", "field_8h" ],
    [ "fieldsample.h", "fieldsample_8h.html", "fieldsample_8h" ],
    [ "globals.h", "globals_8h.html", "globals_8h" ],
    [ "grid_labels.h", "grid__labels_8h.html", "grid__labels_8h" ],
    [ "hdf5_io.h", "hdf5__io_8h.html", "hdf5__io_8h" ],
    [ "input_flags.h", "input__flags_8h.html", "input__flags_8h" ],
    [ "input_matrices.h", "input__matrices_8h.html", "input__matrices_8h" ],
    [ "input_output_names.h", "input__output__names_8h.html", null ],
    [ "interface.h", "interface_8h.html", "interface_8h" ],
    [ "interpolation_methods.h", "interpolation__methods_8h.html", "interpolation__methods_8h" ],
    [ "mat_io.h", "mat__io_8h.html", null ],
    [ "matrix_collection.h", "matrix__collection_8h.html", "matrix__collection_8h" ],
    [ "mesh_base.h", "mesh__base_8h.html", "mesh__base_8h" ],
    [ "numerical_derivative.h", "numerical__derivative_8h.html", "numerical__derivative_8h" ],
    [ "shapes.h", "shapes_8h_source.html", null ],
    [ "simulation_parameters.h", "simulation__parameters_8h.html", "simulation__parameters_8h" ],
    [ "source.h", "source_8h.html", "source_8h" ],
    [ "surface_phasors.h", "surface__phasors_8h.html", "surface__phasors_8h" ],
    [ "timer.h", "timer_8h.html", "timer_8h" ],
    [ "utils.h", "utils_8h.html", "utils_8h" ],
    [ "vertex_phasors.h", "vertex__phasors_8h.html", "vertex__phasors_8h" ]
];