var searchData=
[
  ['tdfieldexporter2d_0',['TDFieldExporter2D',['../class_t_d_field_exporter2_d.html',1,'']]],
  ['tdms_1',['TDMS',['../md_doc_2developers.html#autotoc_md16',1,'Developers' introduction to TDMS'],['../index.html',1,'TDMS']]],
  ['tdms_20·_2',['TDMS · &lt;a href=&quot;https://github.com/UCL/TDMS/releases&quot;&gt;&lt;img src=&quot;https://badgen.net/github/release/UCL/TDMS&quot; alt=&quot;latest release&quot; class=&quot;inline&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://github.com/UCL/TDMS/blob/main/LICENSE&quot;&gt;&lt;img src=&quot;https://badgen.net/badge/license/GPL-3.0/blue&quot; alt=&quot;license&quot; class=&quot;inline&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://github.com/UCL/TDMS/actions/workflows/ci.yml&quot;&gt;&lt;img src=&quot;https://github.com/UCL/TDMS/actions/workflows/ci.yml/badge.svg&quot; alt=&quot;Build and test&quot; style=&quot;pointer-events: none;&quot; class=&quot;inline&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://github.com/UCL/TDMS/actions/workflows/matlab_tests.yml&quot;&gt;&lt;img src=&quot;https://github.com/UCL/TDMS/actions/workflows/matlab_tests.yml/badge.svg&quot; alt=&quot;MATLAB tests&quot; style=&quot;pointer-events: none;&quot; class=&quot;inline&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://codecov.io/gh/UCL/TDMS&quot;&gt;&lt;img src=&quot;https://codecov.io/gh/UCL/TDMS/branch/main/graph/badge.svg?token=3kqP14kslL&quot; alt=&quot;codecov&quot; style=&quot;pointer-events: none;&quot; class=&quot;inline&quot;/&gt;&lt;/a&gt; &lt;a href=&quot;https://zenodo.org/badge/latestdoi/448864310&quot;&gt;&lt;img src=&quot;doc/assets/doi-badge.svg&quot; alt=&quot;DOI:10.5281/zenodo.7950603&quot; style=&quot;pointer-events: none;&quot; class=&quot;inline&quot;/&gt;&lt;/a&gt;',['../index.html#autotoc_md0',1,'']]],
  ['tdms_20algorithm_3',['Code organisation of the TDMS algorithm',['../md_doc_2developers.html#autotoc_md21',1,'']]],
  ['tdms_5fflags_4',['tdms_flags',['../namespacetdms__flags.html',1,'']]],
  ['tdms_5fvector_5futils_5',['tdms_vector_utils',['../namespacetdms__vector__utils.html',1,'']]],
  ['tear_20down_6',['5. Write out and Tear Down',['../md_doc_2developers.html#autotoc_md25',1,'']]],
  ['test_7',['Workflow of a System Test',['../md_doc_2developers.html#autotoc_md27',1,'']]],
  ['test_20coverage_8',['Test coverage',['../md_doc_2developers.html#coverage',1,'']]],
  ['test_5fargument_5fparser_2ecpp_9',['test_argument_parser.cpp',['../test__argument__parser_8cpp.html',1,'']]],
  ['test_5fbli_5fvs_5fcubic_5finterpolation_2ecpp_10',['test_BLi_vs_cubic_interpolation.cpp',['../test___b_li__vs__cubic__interpolation_8cpp.html',1,'']]],
  ['test_5fcase_11',['TEST_CASE',['../test__argument__parser_8cpp.html#a4907558c7fcd2522c5394ecf8cd29558',1,'TEST_CASE(&quot;Test namespace&quot;):&#160;test_argument_parser.cpp'],['../test__argument__parser_8cpp.html#aa6538111875264be4716eaeb61acff79',1,'TEST_CASE(&quot;Test parsing two filenames&quot;):&#160;test_argument_parser.cpp'],['../test__argument__parser_8cpp.html#ab2a81c60462ccfdb087b19f2e9602ef5',1,'TEST_CASE(&quot;Test parsing three filenames&quot;):&#160;test_argument_parser.cpp'],['../test__argument__parser_8cpp.html#a875195d1905da0932a62da584d9ffd8f',1,'TEST_CASE(&quot;Test wrong number of file names&quot;):&#160;test_argument_parser.cpp'],['../test__argument__parser_8cpp.html#adbd8ec307128e35c37ffa7586f3a9b16',1,'TEST_CASE(&quot;CL options&quot;):&#160;test_argument_parser.cpp'],['../test___b_li__vs__cubic__interpolation_8cpp.html#ae2da8b03fb4b6f44dd7cc21624ecac00',1,'TEST_CASE(&quot;Benchmark: BLi is better than cubic interpolation&quot;):&#160;test_BLi_vs_cubic_interpolation.cpp'],['../test__interpolation__determination_8cpp.html#a94ea2527c5944c8b928b52a3e7d0c0a8',1,'TEST_CASE(&quot;best_interp_scheme: correct interpolation chosen&quot;):&#160;test_interpolation_determination.cpp'],['../test__interpolation__functions_8cpp.html#a0040ebab2f5bae0664c62978e4db0d5f',1,'TEST_CASE(&quot;Cubic interpolation: exact for polynomials of degree &lt;= 3&quot;):&#160;test_interpolation_functions.cpp'],['../test__interpolation__functions_8cpp.html#a453f75a33bfd4bcb21ec8f6a6a53cce9',1,'TEST_CASE(&quot;BLi: interpolation-coefficient sums match&quot;):&#160;test_interpolation_functions.cpp'],['../test__numerical__derivative_8cpp.html#a61d20d0fe20a2cc56441a5cbad09226d',1,'TEST_CASE(&quot;Element-by-element multiplication of array of complex numbers&quot;):&#160;test_numerical_derivative.cpp'],['../test__numerical__derivative_8cpp.html#acd950a07968046b93bee2605b348effb',1,'TEST_CASE(&quot;Numerical derivative&quot;):&#160;test_numerical_derivative.cpp']]],
  ['test_5ffieldsample_2ecpp_12',['test_FieldSample.cpp',['../test___field_sample_8cpp.html',1,'']]],
  ['test_5finterpolation_5fdetermination_2ecpp_13',['test_interpolation_determination.cpp',['../test__interpolation__determination_8cpp.html',1,'']]],
  ['test_5finterpolation_5ffunctions_2ecpp_14',['test_interpolation_functions.cpp',['../test__interpolation__functions_8cpp.html',1,'']]],
  ['test_5fnumerical_5fderivative_2ecpp_15',['test_numerical_derivative.cpp',['../test__numerical__derivative_8cpp.html',1,'']]],
  ['test_5futils_2ecpp_16',['test_utils.cpp',['../test__utils_8cpp.html',1,'']]],
  ['test_5fvertexphasors_2ecpp_17',['test_VertexPhasors.cpp',['../test___vertex_phasors_8cpp.html',1,'']]],
  ['testing_18',['Testing',['../md_doc_2developers.html#testing',1,'']]],
  ['tests_19',['Generating Input Data for the System Tests',['../md_doc_2developers.html#autotoc_md28',1,'']]],
  ['the_20algorithm_20code_20',['Navigating the algorithm code',['../md_doc_2developers.html#autotoc_md20',1,'']]],
  ['the_20command_20line_21',['On the command line',['../index.html#autotoc_md7',1,'']]],
  ['the_20data_22',['(Re)generation of the Data',['../md_doc_2developers.html#autotoc_md29',1,'']]],
  ['the_20data_20input_5fgeneration_20directory_20and_20subdirectories_23',['Contents of the &lt;span class=&quot;tt&quot;&gt;data/input_generation&lt;/span&gt; Directory (and subdirectories)',['../md_doc_2developers.html#autotoc_md30',1,'']]],
  ['the_20main_20loop_24',['3. Running the Main Loop',['../md_doc_2developers.html#autotoc_md23',1,'']]],
  ['the_20system_20tests_25',['Generating Input Data for the System Tests',['../md_doc_2developers.html#autotoc_md28',1,'']]],
  ['the_20tdms_20algorithm_26',['Code organisation of the TDMS algorithm',['../md_doc_2developers.html#autotoc_md21',1,'']]],
  ['there_5fare_5fvertices_5fto_5fextract_5fat_27',['there_are_vertices_to_extract_at',['../class_vertex_phasors.html#ad7cb67b33fdff91e2dd1bdb07fb78d21',1,'VertexPhasors']]],
  ['time_20domain_20maxwell_20solver_28',['Time-Domain Maxwell Solver',['../index.html#autotoc_md1',1,'']]],
  ['timer_29',['Timer',['../class_timer.html',1,'']]],
  ['timer_2eh_30',['timer.h',['../timer_8h.html',1,'']]],
  ['to_20contribute_31',['Want to contribute?',['../index.html#autotoc_md10',1,'']]],
  ['to_20run_32',['How to run',['../index.html#autotoc_md5',1,'']]],
  ['to_20tdms_33',['Developers&apos; introduction to TDMS',['../md_doc_2developers.html#autotoc_md16',1,'']]],
  ['to_5fvector_5fint_34',['to_vector_int',['../namespacetdms__vector__utils.html#a89fa17327d197e6c0ce66f9d7dbf1084',1,'tdms_vector_utils']]],
  ['triangulatecuboid_35',['triangulateCuboid',['../mesh__base_8h.html#af542151614a30a9fea3279e6730463fd',1,'mesh_base.cpp']]],
  ['triangulateplane_36',['triangulatePlane',['../mesh__base_8h.html#a33e5a5bb9c09e69af86409399ddfdce9',1,'mesh_base.cpp']]],
  ['triangulateplaneskip_37',['triangulatePlaneSkip',['../mesh__base_8h.html#a5f577c512f3cce916d1effaf7275d46b',1,'mesh_base.cpp']]]
];
