name: Run code linting

on:
  push:
    branches: "main"
  pull_request:
  release:
  workflow_dispatch:

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: ucl/composite-actions/pre-commit@v1
        with:
          python-version: '3.10'
