name: MacOS tests

on:
  push:
    branches: ["main"]
  pull_request:
  release:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Test - ${{ matrix.os }} - Build type ${{ matrix.build_type }} - Build testing ${{ matrix.build_testing }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
        # TODO: can change to macos-latest (but it's currently aliased to macos-11)
        build_type:
          - Release
        build_testing:
          - ON
          - OFF
        # TODO: remove this once MATLAB dependency is removed and mexFunction is replaced
        derivative_type:
          - PS
          - FD
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup cache
        id: cache-test-data
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/tdms/tests/system/data
          key: test_data

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Install dependencies
        run: |
          brew install fftw
      - name: Hack to fix omp headers not linked
        run: |
          brew unlink libomp
          brew link --force libomp

      - name: Install Python dependencies
        shell: bash
        run: |
          pip3 install -r ${GITHUB_WORKSPACE}/tdms/tests/requirements.txt
      - name: Create Build Environment
        run: |
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure TDMS
        shell: bash
        working-directory: ${{runner.workspace}}/build
        env:
          CXXFLAGS: -Werror
        run: |
          cmake ${GITHUB_WORKSPACE}/tdms -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
           -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
           -DBUILD_TESTING=${{ matrix.build_testing }} \
           -DOMP_ROOT=$(brew --prefix libomp) \
           -DDERIVATIVE_TYPE=${{ matrix.derivative_type }}

      - name: Build TDMS
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          cmake --build . --config ${{ matrix.build_type }}
      - name: Run TDMS unit tests
        if: matrix.build_testing == 'ON'
        working-directory: ${{runner.workspace}}/build
        run: |
          export OMP_NUM_THREADS=1
          ctest -C ${{ matrix.build_type }} --output-on-failure --extra-verbose

      # TODO: simplify this once MATLAB dependency is removed and mexFunction is replaced
      - name: Run PSTD TDMS system tests
        # run system tests in mac only on pushes to main (they are a bit slow)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.derivative_type == 'PS' }}
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          export OMP_NUM_THREADS=1
          pytest ${GITHUB_WORKSPACE}/tdms/tests/system/ -s -x  -m "not fdtd_build_only"

      - name: Run FDTD TDMS system tests
        # run system tests in mac only on pushes to main (they are a bit slow)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.derivative_type == 'FD' }}
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          export OMP_NUM_THREADS=1
          pytest ${GITHUB_WORKSPACE}/tdms/tests/system/ -s -x  -m fdtd_build_only
