name: MATLAB tests

on:
  push:
    branches: "main"
  pull_request:
  merge_group:
  release:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.3.0

      - name: Run script
        uses: matlab-actions/run-command@v1
        with:      # rfpcb contains a delta function definition which must be removed so a delta struct can be defined
          command: rmpath([matlabroot '/toolbox/rfpcb/rfpcb/shapes']), run('tdms/tests/matlab/run_tests.m')
