name: Run tests

on:
  push:
    branches: "main"
  pull_request:
  release:
  workflow_dispatch:

jobs:
  tests:
    name: Test - ${{ matrix.os }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        build_type:
          - Release
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libfftw3-dev libgomp1
      - name: Create Build Environment
        run: |
          cmake -E make_directory ${{runner.workspace}}/build
      - name: Configure TDMS
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake ${GITHUB_WORKSPACE}/tdms -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Build TDMS
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          cmake --build . --config ${{ matrix.build_type }}
      - name: Test TDMS
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # This is a dummy test for the time being
        run: ls tdms
