name: Windows tests

on:
  push:
    branches: ["main"]
  pull_request:
  release:
  workflow_dispatch:

jobs:
  tests:
    name: Test - ${{ matrix.os }} - Build type ${{ matrix.build_type }} - Build testing ${{ matrix.build_testing }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        build_type:
          - Release
        build_testing:
          - OFF
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup cache
        id: cache-test-data
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/tdms/tests/system/data
          key: test_data

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Install dependencies
        shell: pwsh
        run: |
          conda install fftw --yes
          echo "FFTWDIR=C:\Miniconda\envs\test\Library" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install Python dependencies
        shell: bash
        run: |
          pip install -r ${GITHUB_WORKSPACE}/tdms/tests/requirements.txt

      - name: Create Build Environment
        run: |
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure TDMS
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake ${GITHUB_WORKSPACE}/tdms -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DBUILD_TESTING=${{ matrix.build_testing }}

      - name: Build TDMS
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          cmake --build . --config Release

      - name: Copy TDMS exe
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          cp Release/* .

      - name: Run TDMS system tests
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          export OMP_NUM_THREADS=1
          export PATH=/c/Program\ Files/MATLAB/R2022a/bin/win64/:$PATH
          export PATH=/c/Miniconda/envs/test/Library/bin/:$PATH
          py.test ${GITHUB_WORKSPACE}/tdms/tests/system/test_cli.py -s -x
